Update 141. Linked List Cycle.cpp
md-shamim-ahmad/LeetCode-Problem-Solution pull request #106
Opened 2023-10-06 15:12 UTC by pandeydhruv2001

- [ ] I have read [CONTRIBUTING.md](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidelines/How%20to%20Add%20a%20new%20Solution%20Code.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All functions and variable names follow **Clean Code** naming conventions.
- [ ] This code follows the clang-format style.

2023-10-10 14:45 UTC, md-shamim-ahmad requested changes
Your code are not correct 
replace your code by the given code if you have any plan for this PR
```cpp
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode(int x) : val(x), next(NULL) {}
 * };
 */
class Solution {
public:
    bool hasCycle(ListNode *head) {
        // Initialize two pointers: fast and slow, and assign them to the head of the list.
        ListNode *fast = head;
        ListNode *slow = head;

        // Traverse the list until fast and fast->next are not NULL.
        // Increment fast by 2 steps and slow by 1 step in each iteration.
        while (fast != nullptr && fast->next != nullptr) {
            fast = fast->next->next;
            slow = slow->next;

            // If fast and slow are at the same address, this means the linked list has a cycle.
            if (fast == slow) {
                return true;
            }
        }

        // If the traversal reaches NULL, this means there is no cycle.
        return false;
    }
};

```

2023-10-10 18:47 UTC, pandeydhruv2001 commented
Changes Done as per the request.

2023-10-10 18:48 UTC, pandeydhruv2001 commented
Changes Done as per the request. Please review and merge

2023-10-11 05:05 UTC, md-shamim-ahmad approved these changes

2023-10-11 05:05 UTC, merged