Create First missing positive
md-shamim-ahmad/LeetCode-Problem-Solution pull request #127
Opened 2023-10-21 19:12 UTC by urvashi-2004

Completed First missing positive problem

2023-10-23 01:36 UTC, md-shamim-ahmad requested changes
Hey thanks for your PR.
But your code file path are not correct.
paste the code into the correct file path location.
For more help, [see the guide](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidelines/How%20to%20Add%20a%20new%20Solution%20Code.md)

2023-10-23 01:36 UTC, md-shamim-ahmad commented on First missing positive
> +}
remove main function from this code.

2023-10-23 01:36 UTC, md-shamim-ahmad commented on First missing positive
> +
remove the header and also namespace

2023-10-23 16:56 UTC, urvashi-2004 commented
Hey @md-shamim-ahmad I have Changed the format. Please review my code and let me know if anything is wrong as I am contributing first time.

2023-10-24 07:23 UTC, urvashi-2004 commented
Hey @md-shamim-ahmad Let me know if anything is left. If not then please check and update to help me get my contribution counted. Thank you !!

2023-10-25 01:58 UTC, md-shamim-ahmad requested changes
hey @urvashi-2004
Your work are really awesome. But you have to change a little.

File name not correct.
If you want to add a leetcode question then file name will be ```README.md```.
As this file contains a leetcode code question then you rename this file as ```README.md``` .

And the path of this file is also incorrect.
Please see the [guidelines](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/Contribution%20Guidelines), then if you do not understand the comment again.

2023-10-25 01:58 UTC, md-shamim-ahmad commented on First missing positive
> +
replace this line
```#41. [First Missing Positive](https://leetcode.com/problems/first-missing-positive/description/)```
by 
```# [41. First Missing Positive](https://leetcode.com/problems/first-missing-positive/description/)```

2023-10-25 03:19 UTC, urvashi-2004 commented
I have replace the line #41. [First Missing Positive](https://leetcode.com/problems/first-missing-positive/description/) by
# [41. First Missing Positive](https://leetcode.com/problems/first-missing-positive/description/)

And I rename my file as README.md. 

Can you tell me the correct file location so that I can resolve this issue because it is showing 404 page not found.

![image](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/assets/85677323/97db203e-37d6-48f7-8a5c-e2e635e8ba0b)

2023-10-25 11:00 UTC, md-shamim-ahmad commented
change this path name or text ```First Missing Positive``` as
![](https://gcdnb.pbrd.co/images/OXH0sh4NQP2j.png?o=1)
<br>
```LeetCode Problems/1 to 100/41. First Missing Positive/README.md```.

hey @urvashi-2004 , 
you just copy ```LeetCode Problems/1 to 100/41. First Missing Positive/README.md``` this text and paste it into ```First Missing Positive``` which I mark by  **read color** then, it will be good.


Please now check this,
[How to Add a new Solution Code](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidelines/How%20to%20Add%20a%20new%20Solution%20Code.md#how-to-add-a-new-solution-code)
[How to Add a Problem README.md File](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidelines/How%20to%20Add%20LeetCode%20Question.md#how-to-add-a-problem-readmemd-file)

2023-10-25 15:03 UTC, urvashi-2004 commented
Now, it's done. You can check and let me know if there is anything left.

2023-10-26 02:55 UTC, urvashi-2004 commented
Hey @md-shamim-ahmad Let me know if anything is left. If not then please check and update to help me get my contribution counted. Thank you !!

2023-10-26 05:09 UTC, md-shamim-ahmad commented
hey @urvashi-2004 
Awesome job.
Do you want to add the solution code to the PR you created?

2023-10-26 05:11 UTC, urvashi-2004 commented
Yes @md-shamim-ahmad can you tell me how can I add solution

2023-10-27 01:14 UTC, md-shamim-ahmad commented
check this link
[How to Add a new Solution Code](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidelines/How%20to%20Add%20a%20new%20Solution%20Code.md#how-to-add-a-new-solution-code)

2023-10-27 01:31 UTC, merged

2023-10-27 02:17 UTC, urvashi-2004 commented
Thank you @md-shamim-ahmad for helping me. you really helped me a lot.