Update SingleNumber Implementation to Use Bitwise XOR #143
md-shamim-ahmad/LeetCode-Problem-Solution pull request #144
Opened 2024-10-01 12:57 UTC by harshendram

I propose updating the implementation to use the XOR bitwise operation, which provides a more efficient solution. The XOR approach has a time complexity of O(n) but reduces the space complexity to O(1), as it does not require any additional data structures.

- [x] I have read [CONTRIBUTING.md](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidelines/How%20to%20Add%20a%20new%20Solution%20Code.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All functions and variable names follow **Clean Code** naming conventions.
- [ ] This code follows the clang-format style.

2024-10-02 10:33 UTC, md-shamim-ahmad requested changes
hi @harshendram 
thanks for your awesome work.
Your proposed solution has really reduced the memory complexity.
nice works

But your code does not follow our **```clang format style```**.
So I think you will solve this ```format``` issue to make this **```PR```** suitable for  **```Merge```** .

2024-10-06 07:34 UTC, harshendram commented
hey thanks for noticing it out , I have done the clang formating what should i do next i am new to this

2024-10-07 00:54 UTC, md-shamim-ahmad approved these changes

2024-10-07 00:56 UTC, md-shamim-ahmad approved these changes
Now it's work good.
Thank you for your contribution!
Looking forward to more contributions from you in the future!

2024-10-07 00:56 UTC, merged