Update 20. Valid Parentheses.cpp
md-shamim-ahmad/LeetCode-Problem-Solution pull request #40
Opened 2023-04-10 17:00 UTC by Md-Shamim-Ahmmed

2023-04-10 17:07 UTC, ahmmed-sde requested changes
Hi,
It will be good if you add the question readme.md file for this problem

2023-04-11 13:59 UTC, ahmmed-sde requested changes

2023-04-11 13:59 UTC, ghost commented on LeetCode Problems/1 to 100/20. Valid Parentheses/20. Valid Parentheses.cpp
> +            else if (s[i] == ']' && stc.top() != '[') return false;
can we reduce those code :
```
else if (s[i] == ')' && stc.top() != '(') return false;                
else if (s[i] == '}' && stc.top() != '{') return false;
else if (s[i] == ']' && stc.top() != '[') return false;
```
as 
```
else if ( 
             (s[i] == ')' && stc.top() != '(') || 
             (s[i] == '}' && stc.top() != '{') || 
             (s[i] == ']' && stc.top() != '[')
)  return false;
```

2023-04-13 10:55 UTC, merged

2023-04-14 17:50 UTC, Md-Shamim-Ahmmed commented on LeetCode Problems/1 to 100/20. Valid Parentheses/20. Valid Parentheses.cpp
> +            else if (s[i] == ']' && stc.top() != '[') return false;
I think they are closely the same.
So no need to change.

2023-07-06 22:01 UTC, Md-Shamim-Ahmmed commented
> Hi, It will be good if you add the question readme.md file for this problem
thanks for your comment ...
[check it now](https://github.com/Md-Shamim-Ahmmed/LeetCode-Problem-Solution/tree/main/LeetCode%20Problems/1%20to%20100/20.%20Valid%20Parentheses)