Create 18. 4 sum
md-shamim-ahmad/LeetCode-Problem-Solution pull request #49
Opened 2023-09-30 18:41 UTC by abhichauhan824

it done @md-shamim-ahmad

2023-10-01 01:36 UTC, md-shamim-ahmad requested changes
nop
in the ```Name your file``` section
![](https://gcdnb.pbrd.co/images/vVNbjPNsbIHk.png?o=1)
<br>
you use ```18. 4Sum / 18. 4Sum.java```.
The symbol ```/``` is used for create a sub folder.

hey you do not need to create anothe PR. You just go to the file and then edit the path.

2023-10-01 01:39 UTC, md-shamim-ahmad requested changes

2023-10-01 01:39 UTC, md-shamim-ahmad commented on LeetCode Problems/1 to 100/18. 4 sum
> +
remove those top three line because you don't need this.

2023-10-01 01:39 UTC, md-shamim-ahmad commented on LeetCode Problems/1 to 100/18. 4 sum
> +        }
remove this main function just

2023-10-03 03:31 UTC, md-shamim-ahmad commented
@abhichauhan824 Do you have any plans for this pull request?

2023-10-03 05:52 UTC, abhichauhan824 commented
@md-shamim-ahmad yes I want to send pull request

2023-10-03 06:15 UTC, md-shamim-ahmad commented
Don't need new PR.
You just modify the code from this file here

2023-10-04 08:28 UTC, md-shamim-ahmad commented
This problem already solve #83 
Thanks for your Contribution

2023-10-04 08:28 UTC, closed without merging