Added Code
md-shamim-ahmad/LeetCode-Problem-Solution pull request #71
Opened 2023-10-03 15:44 UTC by Anubhav-Ghosh1

2023-10-03 15:52 UTC, md-shamim-ahmad requested changes
Though the file name ```ReadMe.md``` and ```README.md``` have no effect.
But I do not have any plane to add a ```.md``` file name which is not same as ```README.md```
So rename the file ```Readme.md``` to ```README.md``` please

2023-10-03 15:52 UTC, md-shamim-ahmad commented on LeetCode Problems/301 to 400/331. Verify Preorder Serialization of a Binary Tree/331. Verify Preorder Serialization of a Binary Tree.cpp
> +
remove those line from here
```cpp
#include <iostream>
#include <bits/stdc++.h>
using namespace std;

```

2023-10-03 15:54 UTC, Anubhav-Ghosh1 commented
Completed changes

2023-10-03 15:55 UTC, Anubhav-Ghosh1 commented
Check it please

2023-10-03 16:04 UTC, Anubhav-Ghosh1 commented
I have completed the changes

2023-10-03 16:05 UTC, md-shamim-ahmad commented
I think you code have bug
```
9,3,4,#,#,1,#,#,2,#,6,#,#
```
Your given solution code **output:** ``` false``` but the answer will be ```true```
Please recheck It.

2023-10-03 16:09 UTC, Anubhav-Ghosh1 commented
Did the changes Accepted
Runtime: 0 ms
Case 1
Case 2
Case 3
Input
![a1](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/assets/88537612/c4578534-5fd7-4c3c-ba80-4765d5bae7a6)

preorder =
"9,3,4,#,#,1,#,#,2,#,6,#,#"
Stdout
0
Output
true
Expected
true

2023-10-03 16:21 UTC, md-shamim-ahmad requested changes
Although the code passed the test case.
But the code does not follow the ```clear code format```.
Use ```clear and meaningful``` **variable** names.

2023-10-03 16:25 UTC, Anubhav-Ghosh1 commented
Made changes

2023-10-03 16:31 UTC, md-shamim-ahmad commented
You use this code 
```cpp
class Solution {
public:
    bool isValidSerialization(string str) {
        int count = 1;
        if (str.size() == 0)
            return 1;
        if (str[0] == '#' and str.size() != 1)
            return 0;
        for (int i = 0; i < str.size(); i++) {
            count -= 1;
            if (count < 0)
                return 0;
            if (str[i] != '#') {
                count += 2;
            }
            i++;
            while (i < str.size() and str[i] != ',') {
                i++;
            }
        }
        if (count == 0)
            return 1;
        return 0;
    }
};
```

2023-10-03 16:33 UTC, Anubhav-Ghosh1 commented
Done

2023-10-03 16:35 UTC, md-shamim-ahmad approved these changes
Thanks for your contribution :)

2023-10-03 16:35 UTC, md-shamim-ahmad commented on LeetCode Problems/301 to 400/331. Verify Preorder Serialization of a Binary Tree/331. Verify Preorder Serialization of a Binary Tree.cpp
> +                c+=2;
where you declare the variable ```c```

2023-10-03 16:37 UTC, merged

2023-10-04 05:41 UTC, Anubhav-Ghosh1 commented
I have made an new code